//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDetail
    {
        public int DId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Hours { get; set; }
        public string TopicsTaken { get; set; }
    }
}
