//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingManagementEntities : DbContext
    {
        public TrainingManagementEntities()
            : base("name=TrainingManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchDetail> BatchDetails { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
    }
}
